swagger: '2.0'
info:
  description: This is the task API.
  version: 1.0.0
  title: Swagger Task api
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
basePath: /v2
tags:
  - name: task
    description: tasks
schemes:
  - http
paths:
  /user:
    post:
      tags:
        - user
      summary: Add a new user
      description: ''
      operationId: addUser
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: User object that needs to be added to the
          required: true
          schema:
            $ref: '#/definitions/user'
      responses:
        '200':
          description: OK
        '405':
          description: Invalid input
    get:
      tags:
        - user
      summary: get a user
      description: ''
      operationId: getUser
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: User object that needs to be found
          required: true
          schema:
            $ref: '#/definitions/user'
      responses:
        '200':
          description: OK
        '405':
          description: Invalid input
  '/user/{userId}':
    get:
      tags:
        - user
      summary: get user by user id
      description: returns a user by id
      operationId: getUserById
      produces:
        - application/json
      parameters:
        - name: userId
          in: path
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
        '405':
          description: Invalid input
    put:
      tags:
        - user
      summary: Add id for user
      description: ''
      operationId: addUserId
      produces:
        - application/json
      parameters:
        - in: path
          name: userId
          description: User id that needs to be added
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: ''
          required: true
          schema:
            $ref: '#definitions/user'
      responses:
        '200':
          description: OK
        '405':
          description: Invalid input
    delete:
      tags:
        - user
      summary: Delete user  by ID
      description: ''
      operationId: deleteUser
      produces:
        - application/json
      parameters:
        - name: userId
          in: path
          description: ID of the user that needs to be deleted
          required: true
          type: integer
          format: int64
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: Id not found
  '/user/{userId}/task':
    get:
      tags:
        - task
      summary: get task for this user
      description: ''
      operationId: getTaskForUser
      produces:
        - application/json
      parameters:
        - name: userId
          in: path
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
        '405':
          description: Invalid input
    post:
      tags:
        - task
      summary: Add new task for user
      description: ''
      operationId: addTaskToUser
      produces:
        - application/json
      parameters:
        - in: path
          name: userId
          description: user id that needs to be given a task
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: ''
          required: true
          schema:
            $ref: '#definitions/user'
      responses:
        '200':
          description: OK
        '405':
          description: Invalid input
  '/user/{userId}/task/{taskId}':
    get:
      tags:
        - task
      summary: get task Id for task by using user id
      description: returns a task id by using id of user
      operationId: getTaskIdByUserId
      produces:
        - application/json
      parameters:
        - name: taskId
          in: path
          required: true
          type: integer
          format: int64
        - name: userId
          in: path
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
        '405':
          description: Invalid input
    put:
      tags:
        - task
      summary: add task id to this task
      description: ''
      operationId: addTaskId
      produces:
        - application/json
      parameters:
        - name: taskId
          in: path
          required: true
          type: integer
          format: int64
        - name: userId
          in: path
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
        '405':
          description: Invalid input
    delete:
      tags:
        - task
      summary: Delete task Id
      description: ''
      operationId: deleteTaskById
      produces:
        - application/json
      parameters:
        - name: taskId
          in: path
          description: ID of the task that needs to be deleted
          required: true
          type: integer
          format: int64
        - name: userId
          in: path
          description: ID of the user for this task
          required: true
          type: integer
          format: int64
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: Id not found
definitions:
  user:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      tasks:
        type: array
        items:
          $ref: '#/definitions/task'
  task:
    type: object
    properties:
      id:
        type: integer
        format: int64
      description:
        type: string
      userid:
        type: integer
